export default {
    messages: {
        error: 'Error',
        success: 'Success',
        info: 'Info',
        'snackbar.dbConnectionError':
            "connection to database couldn't be established.",
        'snackbar.newPasswordAdded': "you've added new password entity!",
        'snackbar.passwordCopiedToClipboard': 'password copied to clipboard.',
        'navBar.howToStart': 'How to start',
        'navBar.pricing': 'Pricing',
        'navBar.authors': 'Authors',
        'navBar.app': 'App',
        'optionsPanel.settings': 'Settings',
        'optionsPanel.decode': 'Decode',
        'optionsPanel.cancel': 'Cancel',
        'optionsPanel.confirm': 'Confirm',
        'optionsPanel.addNew': 'Add new',
        'optionsPanel.add': 'Add',
        'optionsPanel.enterShelfKey': 'Enter your shelf key:',
        'optionsPanel.shelfKeyTooShort': 'Shelf key minimum length is 6.',
        'optionsPanel.labelInputLabel': 'Label',
        'optionsPanel.loginInputLabel': 'Login',
        'optionsPanel.passwordInputLabel': 'Password',
        'optionsPanel.labelTooShort': 'Label minimum length is 4.',
        'optionsPanel.loginTooShort': 'Login minimum length is 6.',
        'optionsPanel.passwordTooShort': 'Password minimum length is 4.',
        'passwordEntity.label': 'Label',
        'passwordEntity.login': 'Login',
        'passwordEntity.password': 'Password',
        'settings.connectToDB': 'Connect to existing database',
        'settings.currentDBConnection:': 'Current database connection',
        'settings.adminKeyLabel': 'FaunaDB admin key',
        'settings.adminKeyLabelDescription':
            'you can find it on your FaunaDB account.',
        'settings.shelfKeyLabel': 'Shelf key',
        'settings.shelfKeyLabelDescription':
            "you'll use that key every time you'll want to decode your passwords. Remember it!",
        'settings.connect': 'Connect',
        'settings.back': 'Back',
        'settings.reConnect': 'Re-connect',
        'settings.noteLabel': 'Note:',
        'settings.noteLabelDescription':
            'if you want to connect to database which already has encoded passwords - use the same shelf key as during initial connection.',
        'settings.adminKeyTooShort': 'Admin key minimum length is 10.',
        'footer.createdBy': 'Created by Marcin Kołodziejczak',
        'banner.ourInterface': 'Our interface',
        'banner.yourDatabase': 'Your database',
        'banner.allPasswords': 'All passwords in one place. For free.',
        'home.howToStart': 'How to start - creating database',
        'home.pricing': 'Pricing',
        'home.authors': 'Authors',
        'home.toStart':
            'To start using this app you need to create a <strong>database</strong> to which your passwords will be stored.',
        'home.followGuide':
            'Follow our <strong>5-step guide</strong> and start the journey!',
    },
};
