export default {
    messages: {
        error: 'Error',
        success: 'Success',
        info: 'Info',
        dbConnectionError: "connection to database couldn't be established.",
        newPasswordAdded: "you've added new password entity!",
        passwordCopiedToClipboard: 'password copied to clipboard.',
        'navBar.howToStart': 'How to start',
        'navBar.pricing': 'Pricing',
        'navBar.authors': 'Authors',
        'navBar.app': 'App',
        'optionsPanel.settings': 'Settings',
        'optionsPanel.decode': 'Decode',
        'optionsPanel.cancel': 'Cancel',
        'optionsPanel.confirm': 'Confirm',
        'optionsPanel.addNew': 'Add new',
        'optionsPanel.add': 'Add',
        'optionsPanel.enterShelfKey': 'Enter your shelf key:',
        'optionsPanel.shelfKeyTooShort': 'Shelf key minimum length is 6.',
        'optionsPanel.labelInputLabel': 'Label',
        'optionsPanel.loginInputLabel': 'Login',
        'optionsPanel.passwordInputLabel': 'Password',
        'optionsPanel.labelTooShort': 'Label minimum length is 4.',
        'optionsPanel.loginTooShort': 'Login minimum length is 6.',
        'optionsPanel.passwordTooShort': 'Password minimum length is 4.',
        'passwordEntity.label': 'Label',
        'passwordEntity.login': 'Login',
        'passwordEntity.password': 'Password',
    },
};
