export default {
    messages: {
        error: 'Błąd',
        success: 'Sukces',
        info: 'Info',
        dbConnectionError: 'połączenie z bazą danych nie powiodło się.',
        newPasswordAdded: 'dodano nowe hasło!',
        passwordCopiedToClipboard: 'skopiowano do schowka.',
        'navBar.howToStart': 'Jak zacząć',
        'navBar.pricing': 'Cennik',
        'navBar.authors': 'Autorzy',
        'navBar.app': 'App',
        'optionsPanel.settings': 'Ustawienia',
        'optionsPanel.decode': 'Odszyfruj',
        'optionsPanel.cancel': 'Anuluj',
        'optionsPanel.confirm': 'Zatwierdź',
        'optionsPanel.addNew': 'Dodaj nowe',
        'optionsPanel.add': 'Dodaj',
        'optionsPanel.enterShelfKey': 'Wprowadź swój klucz półki:',
        'optionsPanel.shelfKeyTooShort':
            'Minimalna długość klucza półki to 6 znaków.',
        'optionsPanel.labelInputLabel': 'Nazwa',
        'optionsPanel.loginInputLabel': 'Login',
        'optionsPanel.passwordInputLabel': 'Hasło',
        'optionsPanel.labelTooShort': 'Minimalna długość nazwy to 4 znaki.',
        'optionsPanel.loginTooShort': 'Minimalna długość loginu to 6 znaków',
        'optionsPanel.passwordTooShort': 'Minimalna długość hasła to 4 znaki.',
        'passwordEntity.label': 'Nazwa',
        'passwordEntity.login': 'Login',
        'passwordEntity.password': 'Hasło',
    },
};
