export default {
    messages: {
        error: 'Błąd',
        success: 'Sukces',
        info: 'Info',
        'snackbar.dbConnectionError':
            'połączenie z bazą danych nie powiodło się.',
        'snackbar.newPasswordAdded': 'dodano nowe hasło!',
        'snackbar.passwordCopiedToClipboard': 'skopiowano do schowka.',
        'navBar.howToStart': 'Jak zacząć',
        'navBar.pricing': 'Cennik',
        'navBar.authors': 'Autorzy',
        'navBar.app': 'App',
        'optionsPanel.settings': 'Ustawienia',
        'optionsPanel.decode': 'Odszyfruj',
        'optionsPanel.cancel': 'Anuluj',
        'optionsPanel.confirm': 'Zatwierdź',
        'optionsPanel.addNew': 'Dodaj nowe',
        'optionsPanel.add': 'Dodaj',
        'optionsPanel.enterShelfKey': 'Wprowadź swój klucz półki:',
        'optionsPanel.shelfKeyTooShort':
            'Minimalna długość klucza półki to 6 znaków.',
        'optionsPanel.labelInputLabel': 'Nazwa',
        'optionsPanel.loginInputLabel': 'Login',
        'optionsPanel.passwordInputLabel': 'Hasło',
        'optionsPanel.labelTooShort': 'Minimalna długość nazwy to 4 znaki.',
        'optionsPanel.loginTooShort': 'Minimalna długość loginu to 6 znaków',
        'optionsPanel.passwordTooShort': 'Minimalna długość hasła to 4 znaki.',
        'passwordEntity.label': 'Nazwa',
        'passwordEntity.login': 'Login',
        'passwordEntity.password': 'Hasło',
        'settings.connectToDB': 'Połącz z bazą danych',
        'settings.currentDBConnection:': 'Połączenie z bazą danych',
        'settings.adminKeyLabel': 'Klucz admina FaunaDB',
        'settings.adminKeyLabelDescription':
            'znajdziesz go na swoim koncie FaunaDB.',
        'settings.shelfKeyLabel': 'Klucz półki',
        'settings.shelfKeyLabelDescription':
            'będzie Ci potrzebny za każdym razem gdy będziesz chciał odszyfrować hasła. Zapamiętaj go!',
        'settings.connect': 'Połącz',
        'settings.back': 'Cofnij',
        'settings.reConnect': 'Połącz ponownie',
        'settings.noteLabel': 'Ważne:',
        'settings.noteLabelDescription':
            'jeśli chcesz połączyć się z bazą danych, która już posiada zaszyfrowane hasła - użyj tego samego klucza półki jak podczas pierwszego połączenia.',
        'settings.adminKeyTooShort':
            'Minimalna długość klucza admina to 10 znaków.',
        'footer.createdBy': 'Stworzone przez Marcina Kołodziejczaka',
    },
};
