export default {
    messages: {
        error: 'Błąd',
        success: 'Sukces',
        info: 'Info',
        dbConnectionError: 'połączenie z bazą danych nie powiodło się.',
        newPasswordAdded: 'dodano nowe hasło!',
        passwordCopiedToClipboard: 'skopiowano do schowka.',
        'navBar.howToStart': 'Jak zacząć',
        'navBar.pricing': 'Cennik',
        'navBar.authors': 'Autorzy',
        'navBar.app': 'App',
        'optionsPanel.settings': 'Ustawienia',
        'optionsPanel.decode': 'Odszyfruj',
        'optionsPanel.cancel': 'Anuluj',
        'optionsPanel.confirm': 'Zatwierdź',
        'optionsPanel.addNew': 'Dodaj nowe',
        'optionsPanel.add': 'Dodaj',
    },
};
